baseURL = 'http://example.org/'
languageCode = 'ru-ru'
title = 'Cоставная страница: блог'
theme="archie"


# Подсветка кода
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

paginate=3 # статей на странице

[params]
	mode="auto" # цветовой режим → светлый, темный, переключатель или автоматический
	useCDN=false # не используйте CDN для шрифтов и значков, вместо этого обслуживайте их локально.
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
	mathjax = true # включить поддержку MathJax
	katex = true # включить поддержку KaTeX
	mainSelections = ["posts"]


# Социальные теги

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"

# Пункты главного меню

[[menu.main]]
name = "Главная"
url = "/"
weight = 1

[[menu.main]]
name = "Все публикации"
url = "/posts"
weight = 2

[[menu.main]]
name = "О нас"
url = "/about"
weight = 3

[[menu.main]]
name = "Теги"
url = "/tags"
weight = 4
